{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "devmind-pipeline.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devmind-pipeline.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
  {{- range .Values.ingressRoute.routes }}
  - match: {{ .match }}
    kind: {{ .kind }}
    services:
    - name: {{ include "devmind-pipeline.fullname" $ }}
      port: {{ $.Values.service.port }}
  {{- end }}
{{- end }}
