apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devmind-pipeline.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devmind-pipeline.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  MLFLOW_TRACKING_URI: {{ .Values.secrets.mlflowTrackingUri | quote }}
